name = "phxwax-ing-v1"
compatibility_date = "2026-06-30"
workers_dev = true
preview_urls = true

[assets]
directory = "./dist"

# Bind to custom domain phxwax.ing
[[routes]]
pattern = "phxwax.ing"
custom_domain = true
